### ISSUE TITLE
Undeclared procedure wrap-text

### ISSUE THREAD

**Issue by melezhik** [masukomi/Prettier-Table#5] opened 2022-11-07 17:19 UTC
Hi! I am trying to use the Prettier-Table in SparrowCI pipeline and got this error:

```
12:47:43 :: tar -xzf source.tar.gz 
[task run: task.raku - tasks/main]
[dump code: task.raku]
[1] use Prettier::Table;
[2] my $table = Prettier::Table.new:
[3]   title => "Rakudo Versions",
[4]   field-names => ["Version", "Status", "Time"],
[5]   sort-by => 'Version',
[6]   align => %('Version' => 'l');
[7]   
[8] for config()<tasks><multi-versions><state><list><> -> $i {
[9]   $table.add-row: [ $i<version>, $i<status>,  $i<time> ];
[10] }
[11] say $table;
[12] 
[task stdout]
[task stderr]
12:48:49 :: ===SORRY!=== Error while compiling /var/.sparrowdo/env/main/.sparrowdo/tasks/main/task.raku
12:48:49 :: ===SORRY!=== Error while compiling /var/.sparrowdo/env/main/.sparrowdo/home#sources/ACA885ED28869CAB91367E5A42B7A6AD99646BF1 (Prettier::Table)
12:48:49 :: Undeclared routine:
12:48:49 ::     wrap-text used at line 1166
12:48:49 :: 
12:48:49 :: 
12:48:49 :: at /var/.sparrowdo/env/main/.sparrowdo/tasks/main/task.raku:1
```

The full log is here - https://ci.sparrowhub.io/report/1549

**Comment by masukomi** [comment] 2022-11-08 14:12
Thanks @melezhik 
Will investigate today and report back.

**Comment by masukomi** [comment] 2022-11-08 14:39
So, `wrap-text` is coming from the `Text::Wrap` package, and I've confirmed that he seems to have invoked it correctly (not that that would explain a "Undeclared routine" error.  Using the following code I was able to invoke the wrapping and it seemed to work fine. 

Judging by the error, and the fact that I seem to be able to invoke the wrapping,  I'm thinking that the problem here is that somehow `Text::Wrap` hasn't been downloaded / made available to the code at runtime. 

note: You probably want to specify a `max-table-width` (see example below). When i tried it without specifying one it just made ridiculously wide tables and never invokes the wrapping.  Honestly I'm not sure how you managed to hit that line without having set it. 🤔

I'm closing this for now, because I think that, after these tests, the problem is on your end. Feel free to re-open if I'm wrong. If so please provide an example that goes 💥 outside of your CI with text I can use to replicate it on my end.  Thanks. 

<img width="861" alt="CleanShot 2022-11-08 at 09 34 53@2x" src="https://user-images.githubusercontent.com/2829/200592588-967918d2-2c56-48f9-b9e5-e193947888ce.png">

```raku
use Prettier::Table;
use Text::Wrap;

my $table = Prettier::Table.new:
title=>"Rakudo Versions",
field-names => ["Version", "Status", "Time"],
sort-by => 'Version',
align => %('Version' => 'l');

my $line = "this line is longer than I want it to be. It should be wrapped but maybe it will blow up. we'll have to find out after i finish tying out all these many many words which are hopefully wide enough.";

$table.max-table-width(80);
$table.add-row: ["1.2.0", 'bad', '4:40'];
$table.add-row: ["2.1.0", 'good', '4:41'];
$table.add-row: ["1.2.1", 'good', '4:42'];
$table.add-row: [$line, $line, $line];

say $table;
```

**Comment by melezhik** [comment] 2022-11-08 15:06
@masukomi  I revisited the log and looks like the issue is more subtle than it seemed at first:

```
12:48:09 :: Downloading https://rakudo.org/dl/rakudo/rakudo-moar-2022.04-01-linux-x86_64-gcc.tar.gz
12:48:11 :: Extracting
12:48:12 :: Updating shims
12:48:12 :: Switching to moar-2022.04
12:48:12 :: Done, moar-2022.04 installed
12:48:12 :: Switching to moar-2022.04
12:48:14 :: ===> Searching for: Prettier::Table
12:48:24 :: ===> Searching for missing dependencies: Text::Wrap
12:48:24 :: ===> Installing: _:ver<0.0.1>:auth<zef:codesections>
12:48:24 :: ===> Installing: Prettier::Table:ver<1.0.0>:auth<zef:masukomi>:api<1>
12:48:24 :: ===> Install [FAIL] for Prettier::Table:ver<1.0.0>:auth<zef:masukomi>:api<1>: ===SORRY!=== Error while compiling /var/.sparrowdo/env/main/.sparrowdo/source/home#sources/ACA885ED28869CAB91367E5A42B7A6AD99646BF1 (Prettier::Table)
12:48:24 :: Undeclared routine:
12:48:24 ::     wrap-text used at line 1166
```

The CI test switches to different rakudos (first to 2022.04 and then to 2022.06 and 2022.07) AND tries to install `Prettier::Table` for every version. It starts with rakudo `2022.04` 

As we see at the log, it fails to do so for `2022.04` for the reason `12:48:24 :: Undeclared routine:
12:48:24 ::     wrap-text used at line 1166`

NOW, the issue is not it only it fails to install, but `zef install` somehow updates local zef index so the next installation attempts ( for rakudos `2022.06` and `2022.07`) give it up thinking the module is already installed, log down below ( in SparkyCI log entries come in reverse order, thus the most recent logs appear in the top ) shows that:

```
12:48:25 :: Downloading https://rakudo.org/dl/rakudo/rakudo-moar-2022.06-01-linux-x86_64-gcc.tar.gz
12:48:25 :: Extracting
12:48:27 :: Updating shims
12:48:27 :: Done, moar-2022.06 installed
12:48:27 :: Switching to moar-2022.06
12:48:28 :: No reason to proceed. Use --force-install to continue anyway
```

So this is combination of zef related bug and installation bug for version `2022.04` at least.

And long story short we end up incorrectly installed (without `Text::Wrap` dependency ) `Prettier::Table` module, which is pretty bad.

**Comment by melezhik** [comment] 2022-11-08 15:27
Here is full use case of the bug for `2022.04` version:

https://ci.sparrowhub.io/report/1615

**Comment by melezhik** [comment] 2022-11-08 16:12
upss , it even has failed on `2022.07` rakudo, I wonder if this is a bug of zef version shipped with rakubrew? Interesting ... I am going to add `zef --version` info into report and let's see ...

**Comment by melezhik** [comment] 2022-11-08 16:30
I need some time to debug here, looks like rakubrew switching does not happen correctly

**Comment by melezhik** [comment] 2022-11-08 16:40
https://github.com/Raku/App-Rakubrew/issues/59

**Comment by melezhik** [comment] 2022-11-08 19:36
Finally, after some changes in rakubrew configuration logic, the bug is reproduced on Debian/RakuBrew/Rakudo 2022.07:


```
[task run: task.bash - tasks/main]
[dump code: task.bash]
[1] set -e
[2] 
[3] version=$(config version)
[4] echo "Use rakudo version: $version"
[5] eval "$(~/.rakubrew/bin/rakubrew init Bash)"
[6] rakubrew download moar-$version
[7] rakubrew switch moar-$version
[8] 
[9] cd source
[10] 
[11] which zef
[12] which raku
[13] 
[14] raku --version
[15] zef --version
[16] 
[17] zef update 
[18] zef install --/test .
[19] 
[task stdout]
19:31:18 :: Use rakudo version: 2022.07
19:31:19 :: Downloading https://rakudo.org/dl/rakudo/rakudo-moar-2022.07-01-linux-x86_64-gcc.tar.gz
19:31:19 :: Extracting
19:31:20 :: Switching to moar-2022.07
19:31:20 :: Done, moar-2022.07 installed
19:31:20 :: Switching to moar-2022.07
19:31:20 :: /home/worker/.rakubrew/versions/moar-2022.07/share/perl6/site/bin/zef
19:31:20 :: /home/worker/.rakubrew/versions/moar-2022.07/bin/raku
19:31:20 :: Welcome to Rakudo™ v2022.07.
19:31:20 :: Implementing the Raku® Programming Language v6.d.
19:31:20 :: Built on MoarVM version 2022.07.
19:31:40 :: v0.14.4
19:31:56 :: ===> Searching for missing dependencies: Text::Wrap
19:32:13 :: ===> Installing: _:ver<0.0.1>:auth<zef:codesections>
19:32:13 :: ===> Installing: Prettier::Table:ver<1.0.0>:auth<zef:masukomi>:api<1>
19:32:13 :: ===> Install [FAIL] for Prettier::Table:ver<1.0.0>:auth<zef:masukomi>:api<1>: ===SORRY!=== Error while compiling /var/.sparrowdo/env/main/.sparrowdo/source/site#sources/ACA885ED28869CAB91367E5A42B7A6AD99646BF1 (Prettier::Table)
19:32:13 :: Undeclared routine:
19:32:13 ::     wrap-text used at line 1166
19:32:13 :: 
19:32:13 :: 
[task stderr]
19:32:13 :: ===> Updating fez mirror: https://360.zef.pm/
19:32:13 :: ===> Updating rea mirror: https://raw.githubusercontent.com/Raku/REA/main/META.json
19:32:13 :: ===> Updated rea mirror: https://raw.githubusercontent.com/Raku/REA/main/META.json
19:32:13 :: ===> Updated fez mirror: https://360.zef.pm/
19:32:13 :: ===SORRY!=== Error while compiling /var/.sparrowdo/env/main/.sparrowdo/source/site#sources/ACA885ED28869CAB91367E5A42B7A6AD99646BF1 (Prettier::Table)
19:32:13 :: Undeclared routine:
19:32:13 ::     wrap-text used at line 1166
19:32:13 :: 
19:32:13 :: 
19:32:13 :: task exit status: 1
19:32:13 :: task tasks/main FAILED
```

https://ci.sparrowhub.io/report/1634

**Comment by melezhik** [comment] 2022-11-08 19:54
I think you should use `Text::Wrap:ver<0.0.3+>` instead of just `Text::Wrap`, this is what @antononcube made when he patched `Pretty-Table` module, zef not guarantee to load the latest version if not specified , and I guess there is some bug in older versions of `Text::Wrap`

**Comment by masukomi** [comment] 2022-12-14 19:48
just pushed version 1.1.3 which switched the dependency to `Text::Wrap:ver<0.0.3+>` from `Text::Wrap` 

No other changes. Let me know if this works for you @melezhik as I don't have a good test case. If so, I'll close this.

**Comment by melezhik** [comment] 2022-12-14 20:49
Hi! Look good now in my pipeline 
https://ci.sparrowhub.io/report/2152

**Comment by masukomi** [comment] 2022-12-16 15:06
Yaaay. 🎉 
Thank you for checking @melezhik . Closing this now.

**Closed as completed by masukomi** 2022-12-16 15:06 UTC

**Comment by melezhik** [comment] 2022-12-16 16:01
👍
